disabled_rules:
  - todo

excluded:
  - .build
  - DerivedData
  - WBShop/Core/.build
  - WBShop/Core/.swiftpm
  - WBShop/DSKit/.build
  - WBShop/DSKit/.swiftpm

identifier_name:
  min_length:
    warning: 1
    error: 1

lenient: false
